feat: automatically halt pool if a node's voting power is too high
KYVENetwork/chain pull request #142
Opened 2023-10-30 13:45 UTC by troykessler

2023-11-01 15:44 UTC, shifty11 requested changes
Can you merge the new v1.4 branch into this one (rapha/funders-module)?
Because there were so many changes especially for the tests.

2023-11-06 13:38 UTC, mbreithecker approved these changes, later dismissed

2023-11-06 15:37 UTC, shifty11 approved these changes

2023-11-06 16:03 UTC, mbreithecker approved these changes

2023-11-06 16:04 UTC, merged